global-variables:
  node: &node
    image: node:18.14.1

  install: &install
    <<: *node
    commands:
      - npm install

  bootstrap: &bootstrap
    <<: *node
    commands:
      - npm run lerna:bootstrap

  build: &build
    <<: *node
    commands:
      - npm run lerna:build

  test: &test
    <<: *node
    commands:
      - npm test

kind: pipeline
name: default

steps:
  - name: pr-install
    <<: *install
    when:
      event:
        - pull_request

  - name: push-install
    <<: *install
    when:
      branch:
        - master
      event:
        - push

  - name: pr-bootstrap
    <<: *bootstrap
    when:
      event:
        - pull_request

  - name: push-bootstrap
    <<: *bootstrap
    when:
      branch:
        - master
      event:
        - push

  - name: pr-build
    <<: *build
    when:
      event:
        - pull_request

  - name: push-build
    <<: *build
    when:
      branch:
        - master
      event:
        - push

  - name: pr-test
    <<: *test
    when:
      event:
        - pull_request

  - name: push-test
    <<: *test
    when:
      branch:
        - master
      event:
        - push

  - name: publish
    <<: *node
    environment:
      NPM_TOKEN:
        from_secret: npm_token
    commands:
      - touch ./.npmrc && echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ./.npmrc
      - git config --global user.email "pakas_vieira_95@hotmail.com"
      - git config --global user.name "PauloIVM"
      - git reset --hard
      - npm run publish
    when:
      branch:
        - master
      event:
        - push

trigger:
  event:
    exclude: [ tag ]
